// packages/solid/demo/src/App.tsx
import { ConfettiOptions, createConfetti } from '@neoconfetti/solid';
import { Component, createEffect, createSignal } from 'solid-js';

const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

const App: Component = () => {
	const { confetti } = createConfetti();
	const [options, setOptions] = createSignal<ConfettiOptions>({});
	const [render, setRender] = createSignal(false);

	createEffect(() => {
		async function run() {
			if (!render) return;

			await sleep(2000);

			setOptions((o) => ({
				...o,
				colors: ['red', 'blue'],
				particleShape: 'circles',
			}));

			await sleep(600);

			// Override entire options, re-triggers the confetti
			setOptions({
				particleCount: 200,
				duration: 3500,
				colors: ['#eee', 'black', 'hotpink' /* Sorry 😅 */],
			});
		}

		run();
	});

	return (
		<>
			<>
				<button onClick={() => setRender(true)}>🎉</button>

				{render() && <div use:confetti={options()} />}
			</>
		</>
	);
};

export default App;

// packages/react/demo/src/App.tsx
import { Confetti, ConfettiOptions } from '@neoconfetti/react';
import { useEffect, useState } from 'react';

function App() {
	const [options, setOptions] = useState<ConfettiOptions>({ destroyAfterDone: false });
	const [render, setRender] = useState(true);

	useEffect(() => {
		setTimeout(() => {
			setOptions((o) => ({ ...o, colors: ['#eee', 'black'] }));
			// explode();
		}, 1000);
	}, []);

	return (
		<>
			<button onClick={() => setRender(false)}>Unrender</button>
			{render && <Confetti className="hello" particleClassName="particle-something" {...options} />}
		</>
	);
}

export default App;
