// packages/solid/src/index.ts
import { confetti, type ConfettiOptions, type ConfettiParticleShape } from '@neoconfetti/core';
import { createEffect, onCleanup, type Accessor } from 'solid-js';

export const createConfetti = () => ({
	confetti: (node: HTMLElement, options: Accessor<ConfettiOptions>) => {
		const { update, destroy } = confetti(node, options());

		onCleanup(destroy);
		createEffect(() => update(options()));
	},
});

export type { ConfettiOptions, ConfettiParticleShape };

// packages/react/src/index.ts
import { confetti, type ConfettiOptions, type ConfettiParticleShape } from '@neoconfetti/core';
import { createElement, useEffect, useRef } from 'react';

interface ConfettiProps extends ConfettiOptions {
	class?: string;
}

export function Confetti({ class: className, ...options }: ConfettiProps) {
	const target_ref = useRef<HTMLElement>(null);
	const instance_ref = useRef<ReturnType<typeof confetti>>();

	useEffect(() => {
		if (typeof window === 'undefined') return;
		if (!target_ref.current) return;

		if (!instance_ref.current) {
			instance_ref.current = confetti(target_ref.current, options);
			return;
		}

		instance_ref.current.update(options);

		return instance_ref.current.destroy;
	}, [options]);

	return createElement('div', { ref: target_ref, className });
}

export type { ConfettiParticleShape, ConfettiProps };
